services:
  - type: web
    name: logistics-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: logistics-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SHIPENGINE_API_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: IMAP_SERVER
        value: imap.gmail.com

databases:
  - name: logistics-db
    plan: free